
spring:
  redis:
    host: localhost
    port: 6379

app:
  guardado: Guardado con éxito
  borrado: Tarea borrada con éxito
  noId: No existe el ID
  duplicado: Duplicado
  actualizacion: Actualización realizada con éxito
  msgError: Ha ocurrido un error severo

springdoc:
  version: 0.0.1
vaadin:
  urlMapping: /ui/*
