
spring:
  redis:
    host: localhost
    port: 6379

app:
  notFound: Gateway not found
  guardado: Saved successfully
  borrado: Peripheral successfully deleted
  actualizacion: Successful update
  msgError: A severe error has occurred

springdoc:
  version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
